#应用程序端口配置
server: 
  port: 20003

#日志配置    
logging: 
    config: classpath:logback.xml

spring:
  freemarker:
    prefix:
    suffix: .ftl
    template-loader-path:
      -  classpath:/templates/
    charset: UTF-8
    requestContextAttribute: rc
    #禁用缓存
    cache: false
    settings:
      template_update_delay: 0
  profiles:
    active: ${spring.profiles.active}
  #热部署配置
  devtools:
    restart:
      #自动重启
      enabled: true
    livereload:
      enabled: true


mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.stt.po

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/eip_oss_db?allowMultiQueries=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 10
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: false
      test-on-return: false
      test-on-borrow: false
      filter: stat,wall,log4j,config
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #webstat
      web-stat-filter.enabled: true
      web-stat-filter.exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #statview
      stat-view-servlet.enabled: true
      stat-view-servlet.allow: 127.0.0.1
      stat-view-servlet.deny: 192.168.0.10
      stat-view-servlet.login-username: root
      stat-view-servlet.login-password: root
      stat-view-servlet.reset-enable: false

---
# 测试环境配置
spring:
  profiles: test

---
# 正式环境配置
spring:
  profiles: prd
